blank_issues_enabled: true
contact_links:
  - name: Perguntas e Discussões
    url: https://github.com/seu-usuario/vanna-ai-odoo/discussions
    about: Por favor, faça perguntas e discuta ideias aqui.
